### ISSUE TITLE
SLIM 量化新pose模型失败！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/PaddleSlim#1034]
Hi，
     1 请问是否有最新的关于调用cmd命令或者相关py文件的slim使用说明文档或者网页链接？
      2 比如要int8量化一个新的模型tinypose 如何调用paddle slim工具实现呢？ 
      3 最新的可用版本是哪个？ 具体使用甚至包括编译说明step by step 可以分享下链接吗？ 
      4 PADDLE SLIM 离线量化跟paddle lite里面提供的opt 带量化选项的功能是不是一致，可以不用slim而直接用opt，离线uint8量化的结果也是一样的吗？
 BR

**Comment by 2050airobert** [comment]
Hi, 
     Any body here?

**Comment by yghstill** [comment]
@2050airobert 请参考PaddleDetection中的demo进行量化训练：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/slim
可以参考quant/picodet_s_416_lcnet_quant.yml 修改后跑tinypose的量化训练
paddle lite里面提供的opt只能量化weight，对模型预测没有加速，需要使用PaddleSlim来做量化

**Comment by 2050airobert** [comment]
hello，
1 如果使用lite里面的opt 也是可以进行tinypose全量化的，而且tinypose也可以正确检测到人的姿态，对吗？
2 opt量化的方式跟lite之前模型一样，支持一条命令搞定，然后你们也确认过了，可以这样理解吗？
   还是说目前只支持PaddleSlim训练量化，而训练后离线量化精度会很差？具体是？
BR

**Comment by yghstill** [comment]
@2050airobert 
1. 如果使用opt的量化是只能量化weight存储的，模型仍能正常预测，但是预测时还是将int8 weight >> fp32 weight，然后在fp32下计算，没有加速效果
2. tinypose模型比较复杂，离线量化精度损失非常大，一般进行量化训练，然后转到paddle lite上进行部署

**Comment by 2050airobert** [comment]
Hi，yghstill
1、第一条实际上可以在lite上做一定的改动，支持定点的反量化，不知道这是不是一个解决思路呢？
2、tinypose int8量化确实损失会大，但有尝试过离线的int16量化吗？ 会不会精度损失跟量化训练差距很小了呢？毕竟离线量化会更节省时间，在有些情况下非常方便。
3、目前支持int16量化模型跑通的板子，lite这边统计过主要有哪些厂商或板子支持吗？
4、是不是可以这么说凡是支持int8量化的板子几乎都支持int16？ 除了一些特殊的板子会支持fp16例外的那些？比如海思。。等？
BR

**Comment by 2050airobert** [comment]
hi，
按照文档指示，
python tools/train.py -c configs/picodet/picodet_s_416_coco_lcnet.yml  --slim_config configs/slim/quant/picodet_s_416_lcnet_quant.yml
wode我的环境如下，我用了cpu版本 set cfg.usegpu = False
![image](https://user-images.githubusercontent.com/8407513/165227905-cda6af99-74e7-4961-b811-dd3c1c876497.png)

综上，有两个问题
1 win10下cpu跑可以吗，必须在gpu环境跑吗？
2 即使picoDet qat量化正常，可tinypose的qat量化，数据集也跟picoDet的coco所有不同吧？或者说除了更换yaml 和 slim yaml应该还有一些地方有差异吧？如果没有差异，为什么p slim 还没发布出来呢？ 

BR

**Comment by yghstill** [comment]
> 综上，有两个问题
> 1 win10下cpu跑可以吗，必须在gpu环境跑吗？
> 2 即使picoDet qat量化正常，可tinypose的qat量化，数据集也跟picoDet的coco所有不同吧？或者说除了更换yaml 和 slim yaml应该还有一些地方有差异吧？如果没有差异，为什么p slim 还没发布出来呢？

@2050airobert  1. CPU可以跑，但是训练速度可能会很慢。2. tinypose的量化配置文件还未发布，但是验证过量化训练，你可以参考：
```yaml
slim: QAT
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/keypoint/tinypose_128x96.pdparams

QAT:
  quant_config: {
    'activation_preprocess_type': 'PACT',
    'weight_quantize_type': 'channel_wise_abs_max', 'activation_quantize_type': 'moving_average_abs_max',
    'weight_bits': 8, 'activation_bits': 8, 'dtype': 'int8', 'window_size': 10000, 'moving_rate': 0.9,
    'quantizable_layer_type': ['Conv2D', 'Linear']}
  print_model: False

epoch: 50
LearningRate:
  base_lr: 0.0005
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 30
    - 45
  - !LinearWarmup
    start_factor: 0.
    steps: 100

TrainReader:
  batch_size: 64

```
