### ISSUE TITLE
paddle.static.Executor执行channel-wise量化模型速度异常

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/PaddleSlim#1402]
### [paddle.static.Executor](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/Executor_cn.html#executor)执行量化模型，在channel-wise模式下，速度异常慢。

解决方法：优化fake dequant kernel

### 复现方式
根据自动化压缩示例: https://github.com/PaddlePaddle/PaddleSlim/tree/v2.3.4/example/auto_compression/nlp
将配置文件./configs/pp-minilm/auto/afqmc.yaml修改为如下，只执行量化训练，产出量化 模型：
```
Global:
  model_dir: ./afqmc/
  model_filename: inference.pdmodel
  params_filename: inference.pdiparams
  task_name: afqmc
  dataset: clue
  batch_size: 16
  max_seq_length: 128
Quantization:
Distillation:
TrainConfig:
  epochs: 1
  eval_iter: 1070
  learning_rate: 2.0e-5
  optimizer_builder:
    optimizer: 
      type: AdamW
    weight_decay: 0.01
  origin_metric: 0.7403
```
执行eval, 发现速度很慢：
```
export CUDA_VISIBLE_DEVICES=0
python run.py --config_path='./configs/pp-minilm/auto/afqmc.yaml'  --eval True
```

## 分析
基于上述自动化压缩示例，通过[profiler工具](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/profiler/Profiler_cn.html#profiler)分析结果如下：
![image](https://user-images.githubusercontent.com/7534971/187627030-292b0e3f-7c07-4566-910b-ad3c511bd5e2.png)

**其中，DequantizeTwoScale执行时间明显异常**

## 解决方案
优化[DequantizeTwoScale](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/fake_dequantize_op.cu.h#L154)
建议参考：https://github.com/PaddlePaddle/Paddle/pull/40772

在PR#40772中，只优化了channel-wise量化训练的速度，对fake量化推理不生效。
因为，在[freeze pass](https://github.com/PaddlePaddle/Paddle/blob/v2.3.2/python/paddle/fluid/contrib/slim/quantization/quantization_pass.py#L930)之前，量化训练网络中的dequant op的scale是一个输入，在freeze pass之后，推理网络中的dequant op的scale设置成了两个输入。先后两种情况，命中的kernel不同。

## 补充

如下图所示，fake_channel_wise_dequantize_max_abs的scales有两个输入，应该分别是weights的scales和input scale.
1. 为什么不能将两个scale乘在一起？是为了推理库的pass更方便的获取到weights scales?
2. 设置这两个scales的代码在哪里？
- 在这里：[_insert_post_channel_dequant_op(](https://github.com/PaddlePaddle/Paddle/blob/1b0b253d58bc4fb7989ddde4b8761d2dd671085b/python/paddle/fluid/contrib/slim/quantization/quantization_pass.py#L1110)

![image](https://user-images.githubusercontent.com/7534971/187620126-ad119495-80a4-40ac-b866-7cf53f0deb86.png)
